[package]
name = "minidsp-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.35.1"
anyhow = "1.0.79"
futures = "0.3.30"
minidsp = { path = "../minidsp-rs/minidsp" }
inputbot = "0.6"